# Generated by Django 3.2 on 2022-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('discriptions', models.TextField()),
            ],
        ),
    ]
