# Generated by Django 3.2 on 2022-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_alter_contact_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='product')),
                ('prise', models.CharField(max_length=20)),
                ('desciption', models.CharField(max_length=10000)),
            ],
        ),
    ]
