# Generated by Django 3.2 on 2022-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='media/product/2022-01-05_01-58-38.png', null=True, upload_to='product'),
        ),
    ]
